/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package litvaksig.index;

import litvaksig.index.excel.BirthRecordsExtractor;

public class App {
    public static void main(String[] args) {
        String filePath = "/Users/xx/Documents/genealogy/litvaksig/KUD-KID-1815-1845-B.xls";
        BirthRecordsExtractor.extractRecords(filePath);
    }
}
